Make default not savething online
FribourgSDP/rad.io pull request #292
Opened 2022-06-04 17:41 UTC by BartLucien

This PR will correct the following things:
* Make it impossible for guest user to save playlist online
* Remove old playlist if the playlist name is changed in edition.
* Do not show save online popup when editing playlist
* Add the link to our video in the ReadMe

2022-06-08 08:11 UTC, sim0mo approved these changes
It's okay

2022-06-09 08:59 UTC, VictorSchneuwly requested changes
A couple of typos

2022-06-09 08:59 UTC, VictorSchneuwly commented on app/src/main/res/values-fr/strings.xml
> +    <string name="guest_cannot_save_online">Il faut être connecté in avec google pour sauver une playlist en ligne</string>
Typo: You can remove the "in" and add a capital letter to Google

2022-06-09 09:04 UTC, VictorSchneuwly commented
Corrected the typos myself since @BartLucien had other obligations

2022-06-09 09:22 UTC, merged